on: push

env:
  # why in the world is this not set by default?
  CI: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run pipeline
      - uses: actions/upload-artifact@v1
        with:
          name: app-${{ runner.os }}
          path: dist
  # nodegit build does not work by default, apt-get install never finished either, and can't specify container conditionally
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v2
      # --unsafe-perm should not be needed with the node Docker image
      # worked fine with runner version 2.164.0, not anymore since 2.165.2
      - run: npm ci --unsafe-perm
      - run: npm run pipeline
      - uses: actions/upload-artifact@v1
        with:
          name: app-${{ runner.os }}
          path: dist
